
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms-pedidos
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: ms-pedido-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7070







##

#spring:
#  application:
#    name: ms-pedidos
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/ms-pedidos
#    username: root
#    password: ""
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /doc/swagger-ui.html
